"""empty message

Revision ID: 82ae161bfe67
Revises: b6f42427570c
Create Date: 2018-02-13 13:06:18.500870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ae161bfe67'
down_revision = 'b6f42427570c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test1', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test1')
    # ### end Alembic commands ###
